{{ define "front.container" -}}
- name: {{ .Chart.Name }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- include "front.env" . | nindent 2 }}
  resources:
    {{- toYaml .Values.resources | nindent 8 }}
  ports:
  - name: http
    containerPort: {{ .Values.app.port }}
    protocol: TCP
    livenessProbe:
      httpGet:
        path: /info
        port: http
      initialDelaySeconds: {{ default .Values.probe.initialDelaySeconds .Values.probe.liveness.initialDelaySeconds }}
      timeoutSeconds: {{ default .Values.probe.timeoutSeconds .Values.probe.liveness.timeoutSeconds }}
      periodSeconds: {{ default .Values.probe.periodSeconds .Values.probe.liveness.periodSeconds }}
      failureThreshold: {{ default .Values.probe.failureThreshold .Values.probe.liveness.failureThreshold }}
      successThreshold: {{ default .Values.probe.successThreshold .Values.probe.liveness.successThreshold }}
    readinessProbe:
      httpGet:
        path: /info
        port: http
      initialDelaySeconds: {{ default .Values.probe.initialDelaySeconds .Values.probe.readiness.initialDelaySeconds }}
      timeoutSeconds: {{ default .Values.probe.timeoutSeconds .Values.probe.readiness.timeoutSeconds }}
      periodSeconds: {{ default .Values.probe.periodSeconds .Values.probe.readiness.periodSeconds }}
      failureThreshold: {{ default .Values.probe.failureThreshold .Values.probe.readiness.failureThreshold }}
      successThreshold: {{ default .Values.probe.successThreshold .Values.probe.readiness.successThreshold }}
{{ if .Values.global.app.configMapName }}
  volumeMounts:
  - name: config
    mountPath: /etc/config
{{- end }}
{{- end }}
